import Head from 'next/head'
import Image from 'next/image'
import { useContext, useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import Button from '../src/components/Button'
import { CartContext } from '../context/CartContext'

export default function Home() {
  
  const[music, setMusics] = useState([])

  

  useEffect(() => {
    axios.get('http://localhost:3000/api/music')
    .then(response => {
      setMusics(response.data)
    })
  },[])

  console.log(music)





  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <span>
          
          
        {music.map(song => {
          return (
            <Button key={song.song} audio={song.song} />
          )
        })}
          
        </span>
      </main>
    </div>
  )
}
